### ISSUE TITLE
Policy/Group/User Application Binding Bug

### ISSUE THREAD

**Issue by digitalconstantin** [goauthentik/authentik#6718] opened 2023-08-31 14:55 UTC
**Describe the bug**
Unable to select either Policy or Group or User to bind to an application.

**To Reproduce**

1. Go and login as admin in authentik
2. Click on Admin Interface
3. Scroll down to Applicatons
4. Click on Applications
5. Click on an app from the list
6. Go to Policy / Group / User Bindings
7. Unable to select either Policy or Group or User for the binding

**Expected behavior**
Should allow you to select either a Policy or a Group or a User for the binding.

**Screenshots**
![Screenshot_20230831_164710](https://github.com/goauthentik/authentik/assets/72179350/f1aa3cab-3733-4913-881b-b2975b59aafc)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.1
-   Deployment: docker-compose

**Additional context**
Was working fine before 2023.8.1 update.

**Comment by BeryJu** [comment] 2023-08-31 14:57
duplicate of #6691

**Closed by BeryJu** 2023-08-31 14:57 UTC
Labels: bug
