### ISSUE TITLE
Curl missing in newest docker image; healthcheck failing (ghcr.io/goauthentik/server:latest)

### ISSUE THREAD

**Issue by XRTce** [goauthentik/authentik#2918] opened 2022-05-21 12:16 UTC
**Describe the bug**
The embedded docker healthcheck fails because the curl command for the check cannot be run. Thus e.g. traefik wont create a route to the authentik server and the service is offline.

**To Reproduce**
1. run the latest docker image (ghcr.io/goauthentik/server:latest)
2. see the healthcheck failing

**Expected behavior**
Curl should be included in the image

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.5.1
 - Deployment: docker-compose
after manually installing curl with apt inside the running container the health check returns to healthy

**Comment by BeryJu** [comment] 2022-05-21 13:41
duplicate of #2915

**Closed by BeryJu** 2022-05-21 13:41 UTC
Labels: bug
