### ISSUE TITLE
Monitoring Endpoints not responding

### ISSUE THREAD

**Issue by djarbz** [goauthentik/authentik#7409] opened 2023-11-02 01:42 UTC
**Describe the bug**
In my container setup, I am querying the health endpoints to check the readiness of the container.
After updating to the latest version this no longer responds with a 2## HTTP code.

**To Reproduce**
Here are the readiness commands in my Systemd file.

```ini
## Configure your monitoring software to send requests to /-/health/live/, which will return a HTTP 204 response as long as authentik is running.
ExecStartPost=/usr/bin/timeout 30 bash -c 'until curl -fsSL http://127.0.0.1:9000/-/health/live; do sleep 1; done'
## You can also send HTTP requests to /-/health/ready/, which will return HTTP 204 if both PostgreSQL and Redis connections can be/have been established correctly.
ExecStartPost=/usr/bin/timeout 30 bash -c 'until curl -fsSL http://127.0.0.1:9000/-/health/ready; do sleep 1; done'
## Both kinds of outpost (proxy and LDAP) listen on a separate port (9300), and can be monitored by sending HTTP requests to /outpost.goauthentik.io/ping
ExecStartPost=/usr/bin/timeout 30 bash -c 'until curl -fsSL http://127.0.0.1:9000/outpost.goauthentik.io/ping; do sleep 1; done'
```

**Expected behavior**
The healthcheck URIs should respond appropriately as [documented](https://goauthentik.io/docs/installation/monitoring).

**Logs**
```
Nov 01 20:36:43 oracle authentik_server[1806666]: {"auth_via": "unauthenticated", "event": "/-/health/live", "host": "127.0.0.1:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "10.0.2.100", "request_id": "c267532826ac4c3d9ba0902d58d24acc", "runtime": 13, "scheme": "http", "status": 404, "timestamp": "2023-11-02T01:36:43.971170", "user": "", "user_agent": "curl/7.76.1"}
Nov 01 20:36:43 oracle authentik_server[1806666]: {"auth_via": "unauthenticated", "event": "/-/health/ready", "host": "127.0.0.1:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "10.0.2.100", "request_id": "a336aefca7b24d3293a736398bd9bf10", "runtime": 12, "scheme": "http", "status": 404, "timestamp": "2023-11-02T01:36:43.994909", "user": "", "user_agent": "curl/7.76.1"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: Podman Quadlet

**Comment by BeryJu** [comment] 2023-11-02 15:34
Duplicate of https://github.com/goauthentik/authentik/issues/7371, TL;DR you're missing the trailing slashes on the live and ready endpoints

**Closed by BeryJu** 2023-11-02 15:34 UTC
Labels: bug
