### ISSUE TITLE
Redis configuration doesn't allow specifing username

### ISSUE THREAD

**Issue by diegopeinador** [goauthentik/authentik#6962] opened 2023-09-24 19:57 UTC
My redis installation uses usernames (besides passwords) to authenticate connections. Authentik configuration is not prepared to handle redis usernames:
https://github.com/goauthentik/authentik/blob/1a50e9f8d0003de15a13cc3b3993c637f3f2d612/authentik/root/settings.py#L189

So I'm getting the error:

> Redis Connection failed, retrying... (AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?) logger=authentik.lib.config timestamp=1695584308.5630276 redis_url=redis://:secret_password@redis.home.diegopeinador.com:6379/0

**Comment by PKizzle** [comment] 2023-10-18 05:04
This is a duplicate of https://github.com/goauthentik/authentik/issues/5348 and will be fixed in https://github.com/goauthentik/authentik/pull/6334.

More extensive support for different Redis configurations will be introduced in https://github.com/goauthentik/authentik/pull/7118.

**Closed** 2023-12-26 01:47 UTC
Labels: wontfix
