### ISSUE TITLE
Recovery flow failing in email stage 

### ISSUE THREAD

**Issue by mmierke** [goauthentik/authentik#7352] opened 2023-10-27 17:34 UTC
**Describe the bug**
I'm new to Authentik and tried to setup the recovery flow as described in the video of cooptainian.
However the flow is failing in the recovery email stage.

**To Reproduce**
1) Logout
2) Hit the "Forgot username or password" link
3) Fill in your correct email address or password
4) Press the continue button

Another way to reproduce it is to run the flow with the flow inspector

**Expected behavior**
I would expect to receive an email to reset my password and to continue.

**Screenshots**
![grafik](https://github.com/goauthentik/authentik/assets/8592609/f1635925-e40b-4252-82f8-d1f2de3b9180)

**Logs**
Output from the events log after using the inspector
Context
{
    "geo": {
        "lat": 51.7174,
        "city": "Paderborn",
        "long": 8.7411,
        "country": "DE",
        "continent": "EU"
    },
    "message": "Traceback (most recent call last):\n  File \"/authentik/flows/views/executor.py\", line 287, in get\n    stage_response = self.current_stage_view.dispatch(request)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/django/views/generic/base.py\", line 143, in dispatch\n    return handler(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/stages/email/stage.py\", line 142, in get\n    self.send_email()\n  File \"/authentik/stages/email/stage.py\", line 121, in send_email\n    send_mails(current_stage, message)\n  File \"/authentik/stages/email/tasks.py\", line 26, in send_mails\n    promise = lazy_group()\n              ^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/canvas.py\", line 1568, in __call__\n    return self.apply_async(partial_args, **options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/canvas.py\", line 1598, in apply_async\n    results = list(self._apply_tasks(tasks, producer, app, p,\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/canvas.py\", line 1775, in _apply_tasks\n    sig.apply_async(producer=producer, add_to_parent=False,\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/canvas.py\", line 400, in apply_async\n    return _apply(args, kwargs, **options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py\", line 202, in apply_async\n    return f(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py\", line 594, in apply_async\n    return app.send_task(\n           ^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/app/base.py\", line 798, in send_task\n    amqp.send_task_message(P, name, message, **options)\n  File \"/ak-root/venv/lib/python3.11/site-packages/celery/app/amqp.py\", line 517, in send_task_message\n    ret = producer.publish(\n          ^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/messaging.py\", line 175, in publish\n    body, content_type, content_encoding = self._prepare(\n                                           ^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/messaging.py\", line 268, in _prepare\n    body) = dumps(body, serializer=serializer)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py\", line 219, in dumps\n    with _reraise_errors(EncodeError):\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 155, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py\", line 45, in _reraise_errors\n    reraise(wrapper, wrapper(exc), sys.exc_info()[2])\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/exceptions.py\", line 34, in reraise\n    raise value.with_traceback(tb)\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py\", line 41, in _reraise_errors\n    yield\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py\", line 220, in dumps\n    payload = encoder(data)\n              ^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/utils/json.py\", line 57, in dumps\n    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/encoder.py\", line 258, in iterencode\n    return _iterencode(o, 0)\n           ^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.11/site-packages/kombu/utils/json.py\", line 45, in default\n    return super().default(o)\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nkombu.exceptions.EncodeError: Object of type MIMEImage is not JSON serializable",
    "http_request": {
        "args": {
            "next": "/"
        },
        "path": "/api/v3/flows/executor/recovery/",
        "method": "GET"
    }
}
User
{
    "pk": 1,
    "email": "",
    "username": "AnonymousUser"
}
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.1
-   Deployment: docker-compose

**Additional context**
I tested my email setup as described in the troubleshooting section. Everything worked fine. Test Mail received

**Comment by igor47** [comment] 2023-10-27 18:10
duplicate of #7322

**Closed** 2023-10-27 18:40 UTC
Labels: bug
