### ISSUE TITLE
Screen did not resize properly

### ISSUE THREAD

**Issue by jamesngob** [goauthentik/authentik#8420] opened 2024-02-05 18:23 UTC
**Describe the bug**
On 4K monitor screen, the Authentik windows did not scale/resize correctly to display all items on it. We need to zoom-out, at 90% of the actual screen to see all items

**To Reproduce**

1. Go to Flows & Stages
2. Click on Stages, then create new stage. Select Duo authenticator Setup Stage
3. Scroll down to the bottom, click "Configuration Flow" drop-down menu
4. See error, the drop-down list get cut off near the bottom, did not show the last item

**Expected behavior**
The list should show all the items or having a "scroll bar" to move up and down

**Screenshots**
Refer to 2 screenshots: Original with missing item and zoom out at 90% to see all item

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.10.7]
-   Deployment: [docker-compose]
-  Windows 10 Pro, 64-bit. Google Chrome, latest version
-  4K monitor at 175% zoom in scale by Windows display setting

![1](https://github.com/goauthentik/authentik/assets/73611762/0c04280b-ef6a-4155-83db-56b85afd8646)
![2](https://github.com/goauthentik/authentik/assets/73611762/aa91a40a-28ff-4290-9074-6d087d8ec68f)

**Comment by BeryJu** [comment] 2024-02-06 11:49
duplicate of #6825, fyi you can write into the text box to filter flows shown in the dropdown which will also make the list shorter

**Closed by BeryJu** 2024-02-06 11:49 UTC
Labels: bug
