### ISSUE TITLE
impersonationRequest undefined when starting impersonation

### ISSUE THREAD

**Issue by sleepy-nols** [goauthentik/authentik#12187] opened 2024-11-25 21:36 UTC
**Describe the bug**
Authentik is giving an error when trying to impersonate an user.
```
RequiredError: Required parameter requestParameters.impersonationRequest was null or undefined when calling coreUsersImpersonateCreate.
```

**To Reproduce**
1. Go to `users`
2. Click on `impersonate` on a user

**Expected behavior**
Impersonation successfully starts

**Screenshots**
n/a

**Logs**
nothing is logged when pressing the button

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2024.10.4]
-   Deployment: docker-compose

**Additional context**
n/a

**Comment by justinpretorius** [comment] 2024-11-26 06:57
also seeing this on 2023.10.4

**Comment by MelvinCou** [comment] 2024-11-26 14:52
Duplicate of #12163

Fixed in #12184

I am waiting for a new release before closing my issue.

**Closed** 2024-11-26 15:43 UTC
Labels: bug

**Comment by jamie-dit** [comment] 2024-12-09 10:16
Issue still happening on 2024.10.4

**Comment by sleepy-nols** [comment] 2024-12-09 12:25
will be fixed in the next release, see above

**Comment by sleepy-nols** [comment] 2024-12-13 00:11
24.10.5 is out, which fixes this issue
