### ISSUE TITLE
Consent stage shown every time: Something went wrong! Please try again later. (DB Key already exists)

### ISSUE THREAD

**Issue by davidus05** [goauthentik/authentik#3280] opened 2022-07-19 10:35 UTC
**Describe the bug**
The consent stage is shown every time, although consent was already given and did not expire, which leads to an exception.

**To Reproduce**
1. Log into authentik
2. Click on an application
3. Give consent
4. Log out
5. Click on the same application
6. Consent stage will appear again
7. Giving consent leads into: "Whoops! Something went wrong! Please try again later."

**Expected behavior**
Consent stage should only be shown once in x days (as configured) and not always. Did work perfectly in versions before authentik 2022.7.

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 127, in challenge_valid
    UserConsent.objects.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(79, 86534e2a-befb-40ae-8581-c2387b4ba06b, ) already exists.

```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2022.7.2
- Deployment: docker-compose

**Comment by BeryJu** [comment] 2022-07-30 18:30
fixed by https://github.com/goauthentik/authentik/commit/9a9ba2560b2d607442905aabbcc5284bb68b5489, included in 2022.7.3

**Comment by tmeuze** [comment] 2022-07-31 20:48
@BeryJu I am still hitting this same error on 2022.7.3. I upgraded straight from 2022.6.x. Same steps to reproduce. Should I open another issue?

<details>
<summary>
Stacktrace
</summary>

```
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 120, in challenge_valid
    UserConsent.objects.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 556, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(4, 4116b732-78ba-4441-ab31-f10a2744c96a, email profile) already exists.
```

</details>

authentik version: 2022.7.3
Deployment: docker-compose

Thank you.

**Comment by ranomier** [comment] 2022-07-31 21:13
Can confirm same issue with 2022.7.3 and saml auth and nextcloud. If logs are needed please ask :)

**Comment by BeryJu** [comment] 2022-08-01 15:35
@ranomier @tmeuze can you please try this docker image https://github.com/goauthentik/authentik/pkgs/container/dev-server/31068058?tag=gh-version-2022.7

**Comment by ranomier** [comment] 2022-08-01 15:38
Yes, will do in about 30mins

**Closed** 2022-08-01 18:07 UTC

**Comment by tmeuze** [comment] 2022-08-02 12:51
Hi @BeryJu , I am now on build hash `e2cf578`, and unfortunately the issue persists. 

<details>
<summary>Stacktrace</summary>
```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 129, in challenge_valid
    UserConsent.objects.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 556, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(4, 669e573e-a847-4219-8378-65785ba217d6, email profile) already exists.
```
</details>

Thanks for your help!

**Comment by BeryJu** [comment] 2022-08-02 12:55
There's actually a later build on the same tag now with https://github.com/goauthentik/authentik/commit/8543e140ef90c85c142a38fe5835241bbad29a8f

**Comment by tmeuze** [comment] 2022-08-02 12:58
> There's actually a later build on the same tag now with [8543e14](https://github.com/goauthentik/authentik/commit/8543e140ef90c85c142a38fe5835241bbad29a8f)

You are awesome. Forgive my ignorance - how does one make use of the dev branch in docker-compose? I simply used the latest image I could find; `docker pull ghcr.io/goauthentik/dev-server:gh-main-1659433152-b2dbc87a4fde471bdc79831e8dd0d09a07549342`

**Comment by BeryJu** [comment] 2022-08-02 13:00
you can use https://github.com/goauthentik/authentik/pkgs/container/dev-server/31154557?tag=gh-version-2022.7

**Comment by tmeuze** [comment] 2022-08-02 13:22
Thank you. I am now on `8543e14`. Much to my chagrin, the same error appears during consent. 

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 137, in challenge_valid
    consent.save()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 556, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(4, 669e573e-a847-4219-8378-65785ba217d6, email profile) already exists.
```
</details>

Sorry to pester. Maybe there's something I'm missing. Should I try to remove consent (not sure how) and start over with any given user?

**Comment by BeryJu** [comment] 2022-08-02 13:31
I've only seen the error happen on SAML requests, which are a bit special because the permissions are empty (since SAML doesn't work that way), but your request seems to be from an OAuth flow
Which application is this? Which OAuth scopes are you requesting? (As a workaround you can switch to the implicit flow)

**Comment by tmeuze** [comment] 2022-08-02 13:41
Huh - I should have tested more thoroughly. This only appears to be an issue with Portainer at the moment. I will investigate a potential issue on that end. 

Thanks for working with me, and thanks so much for the excellent software!

**Comment by BeryJu** [comment] 2022-08-02 13:51
interesting, shouldn't be strictly related to portainer, which scopes do you have configured in that?

**Comment by tmeuze** [comment] 2022-08-02 13:55
I have the default `email openid profile` on both ends.
