### ISSUE TITLE
Proxy Provider not working because of invalid upstream certificate

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#1508] opened 2021-10-01 15:43 UTC
**Describe the bug**
I have a proxy provider using the built-in proxy outpost, which uses an HTTPS upstream with an invalid certificate.
Authentik won't proxy the connection, although "Internal host SSL Validation" is disabled.

**To Reproduce**
1. Use upstream with invalid SSL certificate
2. Disable SSL validation
3. navigate to proxy

**Expected behavior**
The proxy should ignore the invalid certificate

**Screenshots**

**Logs**
{"error":"x509: cannot validate certificate for 10.10.10.2 because it doesn't contain any IP SANs","event":"Error proxying to upstream server","level":"warning","timestamp":"2021-10-01T15:33:10Z"}

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.3
 - Deployment: docker-compose

**Additional context**
I'm not sure if this is a regression in authentik or if something changed on the upstream server, but the proxy was working previously.

**Comment by BeryJu** [comment] 2021-10-02 19:16
Looks like a regression from the new Proxy in 2021.9, I've just looked through the code, can you try to enable upstream cert verification, I think there's just a negation missing.

**Comment by eglia** [comment] 2021-10-05 08:49
It is indeed inverted, when I enable the verification it works. I thought I tried that already, but apparently I didn't wait long enough for the changes to propagate.

**Comment by BeryJu** [comment] 2021-10-05 08:51
Cheers, so thats fixed in 9.5 by https://github.com/goauthentik/authentik/commit/52bbf454e3a18a5f01b8aa549473bb384fa3bc22

**Closed by BeryJu** 2021-10-05 08:51 UTC
Labels: bug
