### ISSUE TITLE
Proxy provider unauthenticated blacklist 

### ISSUE THREAD

**Issue by AR2000AR** [goauthentik/authentik#9760] opened 2024-05-17 11:48 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to protect a app that doesn't support restricting account creation to a list of user (or any other providers). I need to allow all urls except `/` and `/login`. Unfortunately golang regexp don't support negative lookahead and the proxy provider only allows whitelisting paths

**Describe the solution you'd like**
Having an authenticated paths regexp field applied after the unauthenticated one.

**Describe alternatives you've considered**
Another solution would be to support a regexp lib that can do a negative lookahead.

**Additional context**
App in questions in a self hosted [kutt](https://kutt.it/) instance.

**Comment by benedikt-bartscher** [comment] 2024-10-27 00:24
This looks like a duplicate of #5925

**Closed** 2024-10-27 10:18 UTC
Labels: enhancement, enhancement/under_consideration
