### ISSUE TITLE
Is there a way to use forward auth to protect a subfolder?

### ISSUE THREAD

**Issue by anoosa1** [goauthentik/authentik#4091] opened 2022-11-26 05:03 UTC
**Describe your question/**
A clear and concise description of what you're trying to do.
Trying to protect a subfolder using forward auth

**Additional context**
When I set it up it just puts me in an infinite redirect loop.

**Comment by erroltuparker** [comment] 2022-11-30 13:52
I found the config listed here helpful in trying to configure subfolder proxying

https://github.com/goauthentik/authentik/issues/2305

The only issue i'm facing is parsing basic http username and password headers atm

**Comment by Anas-Sherif** [comment] 2022-12-01 04:37
> I found the config listed here helpful in trying to configure subfolder proxying
> 
> #2305
> 
> The only issue i'm facing is parsing basic http username and password headers atm

I have tried this and it works however it only works if you are protecting only 1 subfolder if you try to protect another one it will always redirect you to the first one.
Also as you said http auth doesnt work

**Comment by igorferreir4** [comment] 2023-04-24 19:52
Hi, any progress on this?

It would be a great feature.

**Comment by Anas-Sherif** [comment] 2023-10-12 02:25
Any updates on this?

**Comment by BeryJu** [comment] 2024-04-18 16:21
duplicate of #2305

**Closed by BeryJu** 2024-04-18 16:21 UTC
Labels: question
