### ISSUE TITLE
Unable to create Policy/User/Group Binding

### ISSUE THREAD

**Issue by tmeuze** [goauthentik/authentik#2472] opened 2022-03-12 21:50 UTC
**Describe the bug**
Infinite loading and a console error when attempting to create a Policy/User/Group Binding.

**To Reproduce**
From _Applications > [Application] > Policy/Group/User Bindings tab_:
1. Select Create Binding
2. Select Policy or User or Group tab
3. Select a Policy or User or Group
4. Select Create

**Expected behavior**
A binding to be created and appear in the list

**Screenshots**
![CleanShot 2022-03-12 at 16 44 32](https://user-images.githubusercontent.com/9298659/158036063-6e64ef0d-6f66-4645-ad4f-4a6131abc9dc.png)

**Logs**

Browser (Firefox) Console:
```
Uncaught TypeError: e is undefined
    value PolicyBindingForm.ts:260
    value Form.ts:156
    value Form.ts:130
    value Form.ts:193
    value ModalForm.ts:31
    value ModalForm.ts:77
    value SpinnerButton.ts:65
    handleEvent lit-html.ts:2047
    r helpers.ts:98
    hl trycatch.ts:228
    Ve instrument.ts:536
    _$AI lit-html.ts:2036
    m lit-html.ts:1240
    T lit-html.ts:1582
    _$AI lit-html.ts:1434
    Dt lit-html.ts:677
    update lit-element.ts:165
    performUpdate reactive-element.ts:1302
    scheduleUpdate reactive-element.ts:1234
    _$E_ reactive-element.ts:1206
    requestUpdate reactive-element.ts:1181
    o reactive-element.ts:923
    q reactive-element.ts:906
    En lit-element.ts:115
    rl ModalButton.ts:37
    s SpinnerButton.ts:36
    p lit-html.ts:1181
    T lit-html.ts:1572
    _$AI lit-html.ts:1434
    m lit-html.ts:1240
    T lit-html.ts:1582
    _$AI lit-html.ts:1434
    m lit-html.ts:1240
    T lit-html.ts:1582
    _$AI lit-html.ts:1434
    m lit-html.ts:1240
    T lit-html.ts:1569
    _$AI lit-html.ts:1434
    Dt lit-html.ts:677
    update lit-element.ts:165
    performUpdate reactive-element.ts:1302
    scheduleUpdate reactive-element.ts:1234
    _$E_ reactive-element.ts:1206
    requestUpdate reactive-element.ts:1181
    set reactive-element.ts:707
    value ModalButton.ts:99
    value ModalButton.ts:134
    handleEvent lit-html.ts:2047
    r helpers.ts:98
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3
 - Deployment: docker-compose

**Additional context**
This did not seem to happen in 2022.2, as far as I can recall.

**Comment by 0xcd0e** [comment] 2022-03-12 22:20
Same problem here ever since updating to 2022.3. Error is:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'pk')
    at s.__value (PolicyBindingForm.ts:260:45)
    at Form.ts:156:45
    at Array.forEach (<anonymous>)
    at s.value (Form.ts:130:18)
    at s.value (Form.ts:193:27)
    at s.value (ModalForm.ts:31:34)
    at s.__callAction (ModalForm.ts:77:47)
    at s.<anonymous> (SpinnerButton.ts:65:26)
    at Pn.handleEvent (lit-html.ts:2047:29)
```

**Comment by BeryJu** [comment] 2022-03-13 00:43
duplicate of #2469

**Closed by BeryJu** 2022-03-13 00:43 UTC
Labels: bug
