### ISSUE TITLE
JS Unhandled Promise Rejection

### ISSUE THREAD

**Issue by victorzimmer** [goauthentik/authentik#5552] opened 2023-05-09 10:24 UTC
**Describe the bug**
When attempting to create a new user in the directory the UI encounters a JS error displaying the field for YAML/JSON data. Without this field the UI will not allow the user to submit the form for creating new users.

Issue appears in Safari, but not in Firefox. Other browsers not tested.

**To Reproduce**

0. Use Safari browser
1. Go to Admin panel -> Directory -> Users
2. Click on Create
3. Check console for JS errors
5. Observe in UI that the Attributes field for JSON/YAML is missing

**Expected behavior**
Error is no expected. Expected to be able to add users. :)

**Screenshots**
<img width="1143" alt="Screenshot 2023-05-09 at 12 17 30" src="https://github.com/goauthentik/authentik/assets/715456/94b7d46c-8162-43b6-a7b5-eab6e67748ae">

**Logs**
Attached the error from the JS console.
[AuthentikJSError.txt](https://github.com/goauthentik/authentik/files/11429942/AuthentikJSError.txt)

**Version and Deployment**

-   authentik version: 2023.4.1
-   Deployment: docker container orchestrated by Nomad by Hashicorp

**Additional context**
The same issue would appear sporadically with previous versions of Authentik, but was resolved by closing and re-opening the "Create user" dialog. I'm unsure if the actual error was the same, but the symptom of a non-existent attributes field was the same.

**Comment by BeryJu** [comment] 2023-05-10 17:39
duplicate of #4155

**Closed by BeryJu** 2023-05-10 17:39 UTC
Labels: bug
