### ISSUE TITLE
LDAP provider flow selection inconsistent

### ISSUE THREAD

**Issue by CuteThun** [goauthentik/authentik#4970] opened 2023-03-16 07:45 UTC
**Describe the bug**
I tried to setup LDAP Provider as describe in https://goauthentik.io/docs/providers/ldap/generic_setup.
I don't have public name and testing internal with `authentik_host: https://172.16.13.27/`
If I set `authentik_host_insecure: true` in LDAP Outpost Config I see errors.

**Logs**
Output of docker outpost logs:
```
goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0005570a0, 0x0, {0xc0000b2af8, 0x14})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0005570a0, 0x0, {0xc0005bfe50?, 0xfc7060?, 0xc00047e600?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
        /go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
{"event":"Loaded config from environment","level":"debug","timestamp":"2023-03-16T06:56:16Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2023-03-16T06:56:16Z"}
{"error":"500 Internal Server Error","event":"Failed to run server","level":"panic","timestamp":"2023-03-16T06:56:17Z"}
{"event":"finished shutdown","level":"info","logger":"authentik.outpost.ak-api-controller","timestamp":"2023-03-16T06:56:17Z"}
panic: (*logrus.Entry) 0xc000118460
```

**Version and Deployment:**
 - authentik version: 2023.3.0
 - Deployment: docker-compose

**Comment by BeryJu** [comment] 2023-03-16 10:11
possibly duplicate of #4929, make sure to set a bind flow in the LDAP provider settings

**Comment by CuteThun** [comment] 2023-03-16 14:19
When I edit "LDAP Provider", "Bind flow" is always empty.
![изображение](https://user-images.githubusercontent.com/94168957/225645034-3253805f-7e74-4dc6-b928-4444ace9d489.png)

Based on "Generic Setup" here is my LDAP flow:
![изображение](https://user-images.githubusercontent.com/94168957/225646065-0536db57-00a6-4cbd-82e8-997546212dda.png)

**Comment by CuteThun** [comment] 2023-03-16 14:28
Sure. I select the "LDAP-Test" flow and then "Update". But when I press the edit button again, it's blank.

**Comment by fuomag9** [comment] 2023-03-16 17:26
> Sure. I select the "LDAP-Test" flow and then "Update". But when I press the edit button again, it's blank.

I can reproduce this too, I can't seem to set the flow

**Comment by BeryJu** [comment] 2023-03-16 17:51
I can partially reproduce this, as in when I update the provider it will occasionally say "This field is required" under the bind flow, but changes are always persisted correctly

**Comment by CuteThun** [comment] 2023-03-17 06:18
Just for testing purposes. I don't set any flow in the LDAP Provider, update the changes and get no "This field is required", only "Successfully updated provider".

**Comment by CuteThun** [comment] 2023-03-20 12:52
After updating to version 2023.3.1 the ldap provider works fine. But now I need to press the update button 2 times, because the first update shows "This field is required" for bind flow.

**Closed** 2023-03-23 13:05 UTC
Labels: bug
