### ISSUE TITLE
Login page UI messed up

### ISSUE THREAD

**Issue by j0cross** [goauthentik/authentik#10744] opened 2024-08-03 07:01 UTC
**Describe the bug**
The login page UI  (default-authentication-flow) is messed up after update to version 2024.6.2.
I was able to find a difference into the page source code:
On version 2024.2.2 this part of code is present:
**.pf-c-login__main-body, .pf-c-login__main-header, .pf-c-login__main-header-desc {
    color: var(--ak-dark-foreground);
}**
Which is missing on version 2024.6.2.
Sorry but I'm not a developer so I don't actually know if those information is useful enough, in any case feel free to ask if you need more. 

**Screenshots**
![image](https://github.com/user-attachments/assets/bf3e08bf-98af-421a-9141-49ad0420b607)

![authentik_bug_UI](https://github.com/user-attachments/assets/9b5ec2f2-74a0-4dfd-936a-71f591b7fe43)

**Logs**
I wasn't able to find anything related to this problem into the logs.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.2
-   Deployment: docker-compose

**Comment by bogosavljevic** [comment] 2024-08-03 10:32
I have the same issue after the update to 2024.6.2

**Comment by j0cross** [comment] 2024-08-03 11:42
After some debug I can say that the issue is related to the dark theme only, the light one works just fine.
In my case I had a dark theme on my desktop and automatic theme on autentik, so the dark one was used.

**Comment by StizLor** [comment] 2024-08-03 20:17
this issue was already reported and fixed with a temp release: https://github.com/goauthentik/authentik/issues/10709#issuecomment-2263511291

**Comment by BeryJu** [comment] 2024-08-03 23:46
dupe of #10709, 2024.6.3 will be released either tomorrow or monday

**Closed by BeryJu** 2024-08-03 23:46 UTC
Labels: bug
