### ISSUE TITLE
Device Code Flow

### ISSUE THREAD

**Issue by lewis-green** [goauthentik/authentik#4040] opened 2022-11-20 20:07 UTC
**Describe your question/**
An example of how to use the device flow. I have setup a flow and set it to be used on the tenant, but I cannot get a provider to work with device flow. 

Is there some steps on how to setup or what am I missing?

**Relevant infos**
2022.10.0

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2022.10.0]
 - Deployment: [e.g. helm]

**Additional context**

**Comment by Nayruden** [comment] 2022-12-30 13:15
It took me embarrassingly long to figure out how to get this to work, so I'm leaving these instructions to save folks some time in the future.

First, activate the device code flow for the tenant by going to System -> Tenants. Edit your default tenant, expand the default flows, and set "Device code flow". I used "Pre-Authentication (default-source-pre-authentication)".

Then you can configure a provider and application like usual. The provider needs to be OAuth2. I set my "Redirect URI" for the provider to `*` but I'm not sure if that's necessary.

That's it! Now you can point any OAuth2 client that supports device flow at Authentik. The endpoint is `https://my_authentik.my_tld/application/o/device/`. For example, to test out the first step via curl...

```bash
curl -sd "client_id=MY-PROVIDER-CLIENT-ID&scope=openid email" -H "Content-Type: application/x-www-form-urlencoded" https://AUTHENTIK/application/o/device/
```

**Comment by heoyongun** [comment] 2023-05-15 02:53
> It took me embarrassingly long to figure out how to get this to work, so I'm leaving these instructions to save folks some time in the future.
> 
> First, activate the device code flow for the tenant by going to System -> Tenants. Edit your default tenant, expand the default flows, and set "Device code flow". I used "Pre-Authentication (default-source-pre-authentication)".
> 
> Then you can configure a provider and application like usual. The provider needs to be OAuth2. I set my "Redirect URI" for the provider to `*` but I'm not sure if that's necessary.
> 
> That's it! Now you can point any OAuth2 client that supports device flow at Authentik. The endpoint is `https://my_authentik.my_tld/application/o/device/`. For example, to test out the first step via curl...
> 
> ```shell
> curl -sd "client_id=MY-PROVIDER-CLIENT-ID&scope=openid email" -H "Content-Type: application/x-www-form-urlencoded" https://AUTHENTIK/application/o/device/
> ```

I am struggling with the same issue.
#5566 

The following is working
http://localhost:9000/application/o/device/

But when I do the following to get the token, I get an error.
http://localhost:9000/application/o/token/

Did you solve the problem?


http://localhost:9000/application/o/device/

**Comment by TheDevMinerTV** [comment] 2024-01-20 00:48
> It took me embarrassingly long to figure out how to get this to work, so I'm leaving these instructions to save folks some time in the future.
> 
> First, activate the device code flow for the tenant by going to System -> Tenants. Edit your default tenant, expand the default flows, and set "Device code flow". I used "Pre-Authentication (default-source-pre-authentication)".
> 
> Then you can configure a provider and application like usual. The provider needs to be OAuth2. I set my "Redirect URI" for the provider to `*` but I'm not sure if that's necessary.
> 
> That's it! Now you can point any OAuth2 client that supports device flow at Authentik. The endpoint is `https://my_authentik.my_tld/application/o/device/`. For example, to test out the first step via curl...
> 
> ```shell
> curl -sd "client_id=MY-PROVIDER-CLIENT-ID&scope=openid email" -H "Content-Type: application/x-www-form-urlencoded" https://AUTHENTIK/application/o/device/
> ```

Thank you, mate. Took me embarrassingly long to figure out as well. I was about to open an issue. This needs to get documented properly though.

**Comment by BeryJu** [comment] 2024-04-18 16:17
@TheDevMinerTV this was caused by a bug that was fixed by #9076

**Closed by BeryJu** 2024-04-18 16:17 UTC
Labels: question
