### ISSUE TITLE
On-Demand user sync from a source

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#4391] opened 2023-01-09 12:22 UTC
**Is your feature request related to a problem? Please describe.**
I have an instance that is connected to another AD source. The AD source has over 200,000 users, and there will be probably less than 200 users that will log in through my own instance. I would like to speed up synchronization, free up database usage, and overall avoid having sensitive data on my server that I don't need. On-demand synchronization of users from a source would solve all these issues. 

My usecase for authentic is basically "get the users from the AD, and add my own groups for authorization purposes to it".

There is no useful way for me to filter those users before importing them. Interacting with the AD admins is a tedious process that takes too long for authorizing individual users, which is why we have this setup.

**Describe the solution you'd like**
- Allow sources to not synchronize automatically
- Allow to refresh a user to identify against the source in the login flow. If identified against a source, synchronize that user
  - This has the added benefit that changes at the source will propagate faster for already synced users, and would also make sense with a source that does synchronize automatically.
- Allow admins to initiate the user sync process manually (both for creating new users, and for refreshing existing ones)

**Describe alternatives you've considered**
The current thing is working, but it has downsides as I've mentioned above.

**Additional context**
(none)

**Comment by BeryJu** [comment] 2024-04-18 16:54
duplicate of #5764

**Closed by BeryJu** 2024-04-18 16:54 UTC
Labels: enhancement
