### ISSUE TITLE
User details custom field like mobile number?

### ISSUE THREAD

**Issue by itxworks** [goauthentik/authentik#2203] opened 2022-02-01 08:06 UTC
**Describe your question/**
Hello ... is there a way to add a custom field like mobile number to the user detail page ... ?

Thank you.

**Comment by sevmonster** [comment] 2022-03-01 06:15
Dupe of #2121 and #2338

**Comment by ikogan** [comment] 2022-03-17 15:43
This should now be possible with https://github.com/goauthentik/authentik/pull/2397. I think this can be closed.

**Closed** 2022-03-17 15:52 UTC
Labels: question
