### ISSUE TITLE
Unable to create group binding on application

### ISSUE THREAD

**Issue by 0xcd0e** [goauthentik/authentik#2508] opened 2022-03-16 18:44 UTC
**Describe the bug**
When trying to create a binding on an application of type "Group", the server returns 400 "{"user":["Invalid pk \"0\" - object does not exist."]}". A similar problem was fixed in 2022.3.2, but the problem still exists.

**To Reproduce**
1. Go to the Applications page
2. Select an application
3. Select "Policy / Group / User Bindings"
4. "Create Binding"
5. Select Group
6. Select any group an click Create

**Expected behavior**
A group binding is created for this application

**Logs**
```
{"event": "/api/v3/policies/bindings/", "host": "authentik.domain.com", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 26, "remote": "2axxxff", "request_id": "558663c743344c46b0fe591c5709e10c", "runtime": 36, "scheme": "https", "status": 400, "timestamp": "2022-03-16T18:42:09.584179", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"}

{"event": "Bad Request: /api/v3/policies/bindings/", "level": "warning", "logger": "django.request", "timestamp": 1647456129.5851903}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: docker on unRaid

**Comment by BeryJu** [comment] 2022-03-16 18:46
duplicate of #2496

**Closed by BeryJu** 2022-03-16 18:46 UTC
Labels: bug
