### ISSUE TITLE
worker failing health checks

### ISSUE THREAD

**Issue by salsugair** [goauthentik/authentik#5274] opened 2023-04-17 14:36 UTC
**Describe the bug**
worker container fails health checks, (stat: cannot read file system information for '%m': No such file or directory.)
Note user: root` and the docker socket volume are optional and I removed them from my compose file

**Expected behavior**
health checks flagged passed and container status healthy

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.4.0
 - Deployment: docker-compose

**Comment by salsugair** [comment] 2023-04-17 17:53
<img width="776" alt="Screenshot 2023-04-17 at 8 45 29 PM" src="https://user-images.githubusercontent.com/34657507/232567717-6c98a217-c493-4084-bd8e-2f10ce943f36.png">

docker-compose:
 worker:
    image: ghcr.io/goauthentik/server:2023.4
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    networks:
      - backend

**Comment by septatrix** [comment] 2023-04-17 19:20
I can confirm the bug (and see the same error message when running the healthcheck command inside the container), also without running the container as root user and with not mounting the docker socket.

**Comment by BenjaminSchubert** [comment] 2023-04-17 19:43
I have the same problem, only on `2023.4.0`, as far as I can tell the problem stems from https://github.com/goauthentik/authentik/blob/1a4c6408353ee9fb3b19a6cc476447343bb1d546/lifecycle/ak#L2-L3, those two files are never created in my worker node (I haven't checked the server).

**Comment by BeryJu** [comment] 2023-04-17 19:45
duplicate of #5258

**Closed by BeryJu** 2023-04-17 19:45 UTC
Labels: bug
