### ISSUE TITLE
Random path is automatically added

### ISSUE THREAD

**Issue by Bleala** [goauthentik/authentik#4732] opened 2023-02-20 17:34 UTC
**Describe the bug**
Hello there!

I'm running Authentik almost a year now and i really love it, but sometimes i have a strange behaviour.
For example I'm hosting a `code-server` docker instance which is proxied through Authentik. So far so good. But sometimes after the proxy process is done, there is a random path added to my FQDN.
I open the `code-server` with the following url:
`https://code.example.com`
But after I've been authenticated through Authentik the path automatically switches to
`https://code.example.com/stable-6261075646f055b99068d3688932416f2346dd3b/static/out/vs/base/worker/workerMain.js`
for example.

This is a legit file as you can see on this screenshot:
![Code-Server](https://user-images.githubusercontent.com/51357182/220170131-08ae95c7-ee18-4114-8d74-297f5970af45.png)

It is not always the same path and for other services the paths are different:
For example sometimes if I access my portainer instance a path like `/api/xxx` gets added.

I don't exactly know how often this happens maybe around 25% of the time I access a service which is proxied through Authentik.

Does anyone has an idea what's the problem?

Greetings

**To Reproduce**
1. Access proxied FQDN

**Expected behavior**
No path added

**Screenshots**
See above

**Logs**
Don't have them

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.2 (had this problem also with older versions)
 - Deployment: docker-compose

**Additional context**
Nothing else

**Comment by BeryJu** [comment] 2023-02-20 19:43
This happens due to browsers trying to fetch multiple things at the same time (for example the html page, JS as you've seen above, CSS and images), which overrides the final redirect in the proxy session. In 2023.2 I changed the proxy to prioritise the `?rd` parameter over the redirect in the session, but that didn't seem to change much.

**Comment by Bleala** [comment] 2023-02-22 16:57
@BeryJu oh okay I understand. So this problem is known, I think there won't be a solution for this in the near future or?
It's not a big deal, but sometimes a little bit annoying.

**Comment by BeryJu** [comment] 2023-02-22 17:03
As you already noted that it only happens randomly, it's not easy to reliably reproduce, so as much as I want to fix this, I haven't found a good way to get started

**Comment by BeryJu** [comment] 2023-02-24 10:28
just for consistency, duplicate of #4732

**Closed by BeryJu** 2023-02-24 10:28 UTC
Labels: bug, bug/confirmed

**Comment by RoboMagus** [comment] 2023-02-24 11:43
I've been having this issue for a long time already and have been gathering details as to what might be causing it.
It seems to happen mostly when a session has expired and some form of re authentication is done. It is not restricted to subrequests of the same page though as in the example of the worker js query for vscode. I've also found this happen where responses to queries _of other tabs I've had open_ appearing in the tab that's reauthenticating.

My guess to a solution for the problem is to effectively refresh the page when authentication redirects occur, if that's somehow possible...

How much help would logs be for further investigation of this issue? Cause if it occurs again at some point in the near future I would be able to provide them.
