### ISSUE TITLE
Add a global URL prefix (multi apps on one sub domain), impossible?

### ISSUE THREAD

**Issue by LM1LC3N7** [goauthentik/authentik#9202] opened 2024-04-10 08:26 UTC
**Describe your question**
I have a server, where I want to deploy an application and Authentik using docker.
It's been a lot of hours I try to deploy authentik behind a dedicated URL path, but the server always respond without this path prefix.

* domain name: `sub.domain.tld`
* authentik should be on `sub.domain.tld/sso/<all authentik URL here>`
* application 1 shoud be on `sub.domain.tld/app/<all app URL here>`

Traefik is well configured, but Authentik still answer to requests with its base URL without the `/sso/`.
➡️ Is it possible to explicitely tell to Authentik to use a base URL?

**Relevant info**
Version: last docker image with docker-compose file
Traefik: v3.0, PathPrefix is working on `whoami` image and traefik dashboard

**Screenshots**
Here you can see Authentik responding to the first request on `/sso` (so traefik config is validated) and redirecting to other URLs without the path prefix.

![2024-04-10_10-19](https://github.com/goauthentik/authentik/assets/14235706/753034da-7017-4c62-b8ec-dff597d48e71)

**Logs**
```
authentik-server      | {"auth_via": "unauthenticated", "domain_url": "sub.domain.tld", "event": "/", "host": "sub.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 55, "remote": "172.29.125.27", "request_id": "87e9c5fde2394665bc002bd3c108de68", "runtime": 56, "schema_name": "public", "scheme": "https", "status": 302, "timestamp": "2024-04-10T08:21:22.582053", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:121.0esr) Gecko/20162901 Firefox/121.0esr"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: last version from docker image
-   Deployment: docker-compose.yml

**Comment by LM1LC3N7** [comment] 2024-04-10 09:10
When I compare to this issue, the main difference is that now the default `docker-compose.yml` file does not contains any `proxy` container:
https://github.com/goauthentik/authentik/issues/4509

So it seems it is not my solution.

**Comment by cfradewavecom** [comment] 2024-04-15 12:07
Hello, i am getting the same result, its not a traefik problem. I did not find any config/variable to change base url.
Can anyone confirm this? 

What we would like is to have authentik responding, for example, `https://example.com/sso/<authentik api>`  

Thanks

**Comment by LM1LC3N7** [comment] 2024-04-15 13:12
To me currently it is not possible, so it might be a feature request, not a bug.
The initial page load is working well and traefik is doing his job. But then the loaded javascript code is doing some xhr requests or redirections without using the prefix (probably hard coded).

On my side, I was forced to use a dedicated sub domain, even if I don't wanted this solution.

**Comment by BeryJu** [comment] 2024-08-22 16:57
duplicate of #2305

**Closed by BeryJu** 2024-08-22 16:57 UTC
Labels: question
