### ISSUE TITLE
Allow edit-able flow background paths

### ISSUE THREAD

**Issue by fOmey** [goauthentik/authentik#4340] opened 2023-01-03 01:32 UTC
**Is your feature request related to a problem? Please describe.**
Currently you have to re-upload the flow background you would like to use, this leads to duplicate flow background files in /media.

**Describe the solution you'd like**
Allow custom flow background paths, editable textbox.

**Comment by Lanhild** [comment] 2023-01-23 16:19
Not a fix, but a workaround to this issue is to unmount the `media` volume. This allows you to input a custom URL in the field value, which is easier to add dynamic images hosted on a cdn, for example.

**Comment by sevmonster** [comment] 2023-01-24 19:14
You can also update the SQL directly.
```sql
update authentik_flows_flow set background = 'https://example.com/image.png';
```

**Comment by evilham** [comment] 2024-03-26 12:56
Hey,

FWIW, I reached this solution (there is a somewhat limited UI when editing `default-authentication-flow`):

```sh
> curl -H 'Authorization: Bearer <token>' \
    'https://authentik.internal/api/v3/flows/instances/default-authentication-flow/set_background_url/' \
    --json '{"url": "https://authentik.internal/media/public/background.png"}'
```

By using the different slugs of different flows in the URL parameter (instead of `default-authentication-flow`), I guess it can be done on all flows as asked in #4586.

I'd rather do it like this as it uses the API and gives us some notion of stability :-).

**Comment by BeryJu** [comment] 2024-04-18 16:47
kinda duplicate of #3974, we'll be adding a default background image setting in the brand which will affect flows that don't have a custom image set

**Closed by BeryJu** 2024-04-18 16:47 UTC
Labels: enhancement
