### ISSUE TITLE
2024.12.0 Proxy Outpost Websocket cannot connect

### ISSUE THREAD

**Issue by Skaldar** [goauthentik/authentik#12448] opened 2024-12-22 07:56 UTC
**Describe the bug**
After upgrading form 2024.10.5 to 2024.12.0 my proxy outposts cannot connect to the authentik server through websockets.

When i roll back to 2024.10.5 everything works fine.

**To Reproduce**

1.  change the outpost image to ghcr.io/goauthentik/proxy:2024.12.0
2.  docker compose up - d [--force-recreate]
3. watch the logs and see there is no ws connection

**Expected behavior**
The oupost should connect to the server

**Screenshots**
/

**Logs**
authentik-proxy-1  | {"event":"Loaded config","level":"debug","path":"inbuilt-default","timestamp":"2024-12-22T07:39:41Z"}
authentik-proxy-1  | {"event":"Loaded config from environment","level":"debug","timestamp":"2024-12-22T07:39:41Z"}
authentik-proxy-1  | {"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2024-12-22T07:39:41Z"}
authentik-proxy-1  | {"error":"dial tcp: lookup auth.XXXXXXX.comws on 127.0.0.11:53: no such host","event":"failed to connect websocket","level":"warning","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-12-22T07:39:41Z"}

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12.0
-   Deployment:  docker-compose

**Additional context**
Maybe there is a typo in "dial tcp: lookup auth.XXXXXXX.comws on 127.0.0.11:53". Shouldn't be a space between .com and ws?

**Comment by joriskt** [comment] 2024-12-22 08:54
I'm seeing the same. All my applications are unreachable as ar esult.

**Comment by BeryJu** [comment] 2024-12-22 15:36
duplicate of #12430, will be fixed with 2024.12.1 early next week

**Closed by BeryJu** 2024-12-22 15:36 UTC
Labels: bug
