### ISSUE TITLE
LDAP Provider: Insufficient Access Rights

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#1651] opened 2021-10-20 13:45 UTC
**Describe the bug**
Sometimes when doing an LDAP lookup, the outpost returns `Code 50 "Insufficient Access Rights"`.

**To Reproduce**
Have not found a way to reliably reproduce...

**Expected behavior**

**Screenshots**

**Logs**
LDAP outpost:
```2021/10/20 13:11:45 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": access denied```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.8
 - Deployment: docker-compose

**Additional context**
I'm using authentik-ldap as backend for postfix & dovecot authentication. Everything works fine (although queries are very slow), except that sometimes, seemingly randomly, lookups fail with code 50. I can't reproduce it with manual ldapsearch or postmap, it only sometimes happens "in the wild". The lookups attempted by postfix seem correct, using the correct bind user which is part of the authentik group specified as search group of the provider.

I realize that this is difficult to debug, but maybe you could provide some insight into what could cause the "access denied" error.

postfix config:
```
bind             = yes
bind_dn = CN=ldap,OU=users,DC=goauthentik,DC=com
bind_pw = supersecret
query_filter = (mailbox=%s)
result_attribute = mailbox
search_base = OU=users,DC=goauthentik,DC=com
server_host = authentik-ldap:3389
start_tls = no
version          = 3
timeout = 30
debuglevel = -1
```

**Comment by kubino148** [comment] 2021-11-08 13:08
Experiencing the same bug as above, around 1 in 20 LDAP search requests gets denied with Code 50. Quite annoying considering that it fails some automatic deployments that have helm charts in Nexus that uses LDAP to authenticate.

**Comment by BeryJu** [comment] 2021-11-08 13:42
With this bugfix the issue shouldn't happen anymore, it will be included in 10.3 which is due soon.

**Comment by eglia** [comment] 2021-11-10 14:30
I updated to 2021.10.3 yesterday, and unfortunately I had the error again today. So it seems the bug is not yet fixed.

**Comment by kubino148** [comment] 2021-11-12 12:44
Can confirm that after upgrade the bug still persists.
`2021/11/12 12:30:25 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": access denied`

**Comment by BeryJu** [comment] 2021-11-12 16:53
@eglia @kubino148 I assume it happens for both of you randomly, without any pattern?

**Comment by kubino148** [comment] 2021-11-12 17:03
@BeryJu yes, i have around 20 jobs that pull helm repositories from Nexus that is connected to the LDAP outpost and sometimes 1-3 of these jobs will fail to authenticate. It also happened to me once when i was simply trying to manually log in to the Nexus panel. I can provide more details if you need some extended information.

**Closed** 2021-11-12 23:26 UTC
Labels: bug

**Comment by BeryJu** [comment] 2021-11-12 23:27
Right, I was able to reproduce it; the issue is caused by the outpost refresh (which runs periodically and whenever the Outpost/Provider is saved), which doesn't keep the memory which users can bind, so each refresh it would cause the error.

The fixed version will be on gh-next shortly and can be tried with 2021.10.4

**Comment by AlphaJack** [comment] 2022-02-27 19:49
Same error on 2022.2 after changing the base DN
