### ISSUE TITLE
Can't edit attributes when using Firefox

### ISSUE THREAD

**Issue by tomlawesome** [goauthentik/authentik#3777] opened 2022-10-13 12:49 UTC
**Describe the bug**
When using Firefox, I can't edit the user attributes (or use any fields like that). 

**To Reproduce**
Login to Authentik
Go to edit user attributes
Try to edit attributes

**Expected behavior**
I can edit in the brower

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.9.1
 - Deployment: docker-compose

**Additional context**
Works fine in Edge with no changes.

**Comment by BeryJu** [comment] 2022-10-13 15:19
Potentially duplicate of https://github.com/goauthentik/authentik/issues/3627?

**Comment by tomlawesome** [comment] 2022-12-03 12:29
> Potentially duplicate of #3627?

Does not appear to be. 

I also have a very similar issue currently with uploading a logo to an application. There are no errors with regards to uploading and perms are fine, as this functionality previously worked (most apps have a logo). It's as if the authentik webUI does not register the input to the form in any way. Hard to describe, so here's a video related to this specific issue: 

https://user-images.githubusercontent.com/76453276/205440648-fd207922-6af3-44c1-8b6e-473f3b2522fc.mp4

And another showing the logo issue: 

https://user-images.githubusercontent.com/76453276/205440977-0588f381-4f58-4f8f-b0b5-c1056f01ef8c.mp4

**Comment by Maffsie** [comment] 2022-12-05 16:50
I've been experiencing this since at least 2022.10.0, or at least I noticed it with that version. Upgraded to 2022.11.3 and it's still present. I'm using Orion (which is a derivative of Safari). The developer console has only one error, an Unhandled Promise: TypeError message, which seems related to styling, rather than actual logic.

**Comment by Maffsie** [comment] 2022-12-05 23:48
It's definitely front-end - not only because using another browser works, but also because using the API browser tool in Orion to manually submit new user attributes worked fine.

**Comment by tomlawesome** [comment] 2022-12-09 10:02
I just updated to 2022.11.3 and the error seems to have cleared. Too early to say if it's actually fixed, or just yet to reoccur. Seems unlikely to be fully fixed as Maffsie is already running 2022.11.3 and experiencing the issue.

**Comment by BeryJu** [comment] 2022-12-09 12:20
I can't reproduce this error in firefox 107 or 108, the icon upload issue @tomlawesome is fixed by https://github.com/goauthentik/authentik/commit/d5329432fed9ed2a025ca0f7f3aa0317b44cfa85 and the issue @Maffsie is having is related to safari being...safari, and seems to work on the first time opening a form and then after reloading the page

**Closed** 2023-02-15 07:54 UTC
Labels: bug, wontfix
