### ISSUE TITLE
Subdomain version-2024-4 is missing in goauthentik.io SSL cert SAN list

### ISSUE THREAD

**Issue by ilya-vv** [goauthentik/authentik#10346] opened 2024-07-03 08:13 UTC
**Describe the bug**
Subdomain version-2024-4 is missing in goauthentik.io SSL cert SAN list.

**To Reproduce**

1. Open URL [https://version-2024-4.goauthentik.io/docs](https://version-2024-4.goauthentik.io/docs)
2. Get ERR_CERT_COMMON_NAME_INVALID error in browser
3. Run command `openssl s_client -connect version-2024-4.goauthentik.io:443 </dev/null 2>/dev/null | openssl x509 -noout -ext subjectAltName`

**Expected behavior**
Provided URL opens without any issues.

**Logs**
Command `openssl s_client -connect version-2024-4.goauthentik.io:443 </dev/null 2>/dev/null | openssl x509 -noout -ext subjectAltName | sed -E 's/, /\n/g'` output:

```
X509v3 Subject Alternative Name: 
    DNS:docs.goauthentik.io
DNS:version-0-13.goauthentik.io
DNS:version-0-14.goauthentik.io
DNS:version-2021-1.goauthentik.io
DNS:version-2021-2.goauthentik.io
DNS:version-2021-3.goauthentik.io
DNS:version-2022-10.goauthentik.io
DNS:version-2022-11.goauthentik.io
DNS:version-2022-12.goauthentik.io
DNS:version-2022-2.goauthentik.io
DNS:version-2022-3.goauthentik.io
DNS:version-2022-5.goauthentik.io
DNS:version-2022-6.goauthentik.io
DNS:version-2022-7.goauthentik.io
DNS:version-2022-8.goauthentik.io
DNS:version-2022-9.goauthentik.io
DNS:version-2023-1.goauthentik.io
DNS:version-2023-10.goauthentik.io
DNS:version-2023-2.goauthentik.io
DNS:version-2023-3.goauthentik.io
DNS:version-2023-4.goauthentik.io
DNS:version-2023-5.goauthentik.io
DNS:version-2023-6.goauthentik.io
DNS:version-2023-8.goauthentik.io
DNS:version-2024-2.goauthentik.io
```

**Version and Deployment (please complete the following information):**

-   authentik version: https://goauthentik.io
-   Deployment: -

**Additional context**
-

**Comment by ilya-vv** [comment] 2024-07-03 08:16
That's even worse. goauthentik.io uses HSTS and I can't bypass SSL cert error in browser.

```
You cannot visit version-2024-4.goauthentik.io right now because the website uses HSTS.
Network errors and attacks are usually temporary, so this page will probably work later.
```

**Comment by BeryJu** [comment] 2024-07-04 12:16
This is fixed now, was caused by some weirdness in netlify

**Closed by BeryJu** 2024-07-04 12:16 UTC
Labels: bug
