### ISSUE TITLE
Redirect URI Error in 2024.10.3 The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).

### ISSUE THREAD

**Issue by MFYDev** [goauthentik/authentik#12136] opened 2024-11-21 17:02 UTC
After upgraded to 2024.10.3, the domain level forward auth url match got fully messed up, the matching uri which was working well in 2024.10.2 is not working anymore, Allowed Redirect URIs become like this
[RedirectURI(matching_mode=RedirectURIMatchingMode.STRICT, url='https://fmydomainoutpost.goauthentik.io/callback\\?X-authentik-auth-callback=true'), RedirectURI(matching_mode=RedirectURIMatchingMode.STRICT, url='https://mydomain\\?X-authentik-auth-callback=true')]

Now I cannot log in anymore

**Comment by mathieuruellan** [comment] 2024-11-21 17:10
hello @MFYDev..

I've got the same issue.

**Comment by BeryJu** [comment] 2024-11-21 17:15
duplicate of #12135

**Closed by BeryJu** 2024-11-21 17:15 UTC
Labels: bug
