### ISSUE TITLE
Missing space after application name in german translation

### ISSUE THREAD

**Issue by mschewie5** [goauthentik/authentik#9957] opened 2024-06-03 10:53 UTC
**Describe the bug**
In File web/xliff/de.xlf Line 4998 -4999
[Line in File](https://github.com/goauthentik/authentik/blob/main/web/xliff/de.xlf#L4998).
missing space after application name. Translation bug, because there is a word after the name in german, but not in many other languages.

**To Reproduce**
- Navigate to Page of Application
- got redirected to Authentik
- Login Screen shows on german translation: " Anmelden um mit 'Aplication-Name'fortzufahren." (Please see at screenshot).

**Expected behavior**
A visible space after the name.

**Screenshots**
![grafik](https://github.com/goauthentik/authentik/assets/24593723/da9e715f-78cb-43f0-bcdd-26d94ea0222c)
![grafik](https://github.com/goauthentik/authentik/assets/24593723/55f015e7-683e-4392-a7d7-e9dcbd524553)

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2024.4.2]
-   Deployment: [docker-compose]

**Additional context**
Is it possible to change this text via ui or custom.css?

**Comment by BeryJu** [comment] 2024-06-03 15:35
duplicate of #9769, this is fixed in main

**Closed by BeryJu** 2024-06-03 15:35 UTC
Labels: bug
