### ISSUE TITLE
PostgreSQL connection failed,

### ISSUE THREAD

**Issue by 2ndwonder** [goauthentik/authentik#3791] opened 2022-10-14 23:28 UTC
After the latest update of Postgres, my authentic stopped working.. how to fix this? 

PostgreSQL connection failed, retrying... (could not translate host name "authentik-postgres"

level=infologger=authentik.lib.configtimestamp=1665789923.432147
add event=PostgreSQL connection failed, retrying... (could not translate host name "authentik-postgres" to address: Name or service not known )
add level=info
add logger=authentik.lib.config
add timestamp=1665789923.432147
15/10/2022 1:25:23

**Comment by 2ndwonder** [comment] 2022-10-16 01:54
Really? nobody is responding to this.. whatever. I reverted back to 14.5

**Comment by BeryJu** [comment] 2022-10-16 13:25
The error is caused by the postgres container name to resolving, due to postgres not running, as it can't be updated by simply pulling the latest version of the postgres image. Hence the postgres tag is fixed in the default docker-compose file. Also stop with the passive aggressive bumps, replies to issues here are best-effort

**Closed by BeryJu** 2022-10-16 13:25 UTC
Labels: bug
