### ISSUE TITLE
Hashicorp Vault integration broken after upgrade to 2024.10.0

### ISSUE THREAD

**Issue by mxhash** [goauthentik/authentik#11912] opened 2024-11-04 21:07 UTC
**Describe the bug**
Fetch token for Hashicorp Vault is broken after Upgrade to 2024.10.0. Configuration for OIDC has not changed and Authentik response for the token fetch with a 405 "Method not allowed". The token should be fetched with Post.

**To Reproduce**

1. Login to Hashicorp Vault with OIDC

**Expected behavior**
Token is fetched and Vault is is authenticated with a valid session

**Screenshots**

<img width="568" alt="Screenshot 2024-11-04 at 21 55 23" src="https://github.com/user-attachments/assets/c591c052-6fef-4830-bdce-32f23c02c3a6">

**Logs**

```
# docker-compose
server-1  | {"auth_via": "oauth_client_secret", "domain_url": "id.netways.de", "event": "/application/o/token/", "host": "id.netways.de", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 41217, "remote": "185.11.255.68", "request_id": "acf14b4ae5c049798b3a0ea79e1709a7", "runtime": 372, "schema_name": "public", "scheme": "https", "status": 405, "timestamp": "2024-11-04T20:50:48.428335", "user": "", "user_agent": "Go-http-client/1.1"}
server-1  | {"auth_via": "oauth_client_secret", "domain_url": "id.netways.de", "event": "/application/o/token/", "host": "id.netways.de", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 41217, "remote": "185.11.255.68", "request_id": "6c08cee1434b4c618dbcc5db88a52ec7", "runtime": 445, "schema_name": "public", "scheme": "https", "status": 405, "timestamp": "2024-11-04T20:50:48.973373", "user": "", "user_agent": "Go-http-client/1.1"}

# nginx proxy
185.11.255.68 - 3KdD7epmLJEAI4OnhrQ0yynxg180qCZrfbhcn4DT [04/Nov/2024:21:59:01 +0100] "POST /application/o/token/ HTTP/1.1" 405 23 "-" "Go-http-client/1.1" "-"
185.11.255.68 - - [04/Nov/2024:21:59:02 +0100] "POST /application/o/token/ HTTP/1.1" 405 23 "-" "Go-http-client/1.1" "-"
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.0
-   Deployment: docker-compose, nginx proxy

**Comment by BeryJu** [comment] 2024-11-04 23:17
caused by #11879, will be released in 2024.10.1

**Closed by BeryJu** 2024-11-04 23:17 UTC
Labels: bug
