### ISSUE TITLE
Authentik’s enrollment/unenrollment flow upgrading

### ISSUE THREAD

**Issue by headstack** [goauthentik/authentik#6792] opened 2023-09-07 07:57 UTC
**Is your feature request related to a problem? Please describe.**
Now if someone has an LDAP federation with Authentik, they enroll a user and there's no ability to sync it back to LDAP as well as it belonging to some of the federated groups.

**Describe the solution you'd like**
Sync a user and its membership data (I mean the information what group/groups a user belongs to) back to LDAP or any other federation that does supports SCIM or LDAP functionality. It'll make it more valuable to use. 

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by BeryJu** [comment] 2024-07-18 16:20
duplicate of #3896

**Closed by BeryJu** 2024-07-18 16:20 UTC
Labels: enhancement
