### ISSUE TITLE
When user tries to resend the email to reset password they get an error

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1866] opened 2021-12-01 06:02 UTC
**Describe the bug**
User tries to reset their password, and the second they click on resend link, it greets an user with error.

**To Reproduce**
1. Create a user
2. Setup mail
3. Try to reset password
4. Click on the resend link.
5. See error

**Expected behavior**
It would just work and not error out.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/144180357-483c5993-42d5-4b90-83bf-6bb9f77b3136.png)

**Version and Deployment (please complete the following information):**
 - authentik version:2021.10.4
 - Deployment: Ansible with Docker containers

**Additional context**
This is the default recovery flow.

**Comment by BeryJu** [comment] 2021-12-01 07:56
Duplicate of https://github.com/goauthentik/authentik/issues/1791, will be fixed in the next release.

**Closed by BeryJu** 2021-12-01 07:56 UTC
Labels: bug
