### ISSUE TITLE
Passwordless login using email magic link

### ISSUE THREAD

**Issue by drigolin** [goauthentik/authentik#5012] opened 2023-03-20 15:29 UTC
It can be userfull to implement a passwordless login using a "magic link" sent the user private email and have te user loggin in by clicking on the received link.
A variation can be senting an OTP via EMAIL or SMS to have user to not setup a real password but the login process will rely on the "secure" channel like email or SMS.

**Comment by BeryJu** [comment] 2023-03-20 15:48
duplicate of #3291

**Closed by BeryJu** 2023-03-20 15:48 UTC
Labels: enhancement

**Comment by nicoduck** [comment] 2024-06-07 19:13
The other issue is about sending OTPs via E-Mail, while this is about sending a magic-link via E-Mail, as also noted here: https://github.com/goauthentik/authentik/issues/3291#issuecomment-1899322005
The Magic link could (should) directly login the session and could (depending on the implementation) even be used at another machine.

**Comment by thibaultmol** [comment] 2026-04-18 22:12
@BeryJu @melizeche this isn't a duplicate, please reopen

**Comment by dewi-tik** [comment] 2026-04-23 16:19
Will be adding an example that can be imported and achieve this with an email stage and a login stage
