### ISSUE TITLE
Outpost Creation Missing Config Fields on Safari

### ISSUE THREAD

**Issue by seandonohoo** [goauthentik/authentik#6055] opened 2023-06-23 17:01 UTC
**Describe the bug**
When creating an outpost via the web gui the configuration part is blank/doesn't show. 

![image](https://github.com/goauthentik/authentik/assets/542109/90b64d2e-0fe4-4459-a2a9-2c00d4706915)

**To Reproduce**
Safari - `[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15]`

1. Navigate to authentik admin panel
2. Create new Outpost
3. Configuration option is blank therefore not allowing an outpost to be created

**Expected behavior**
Outpost configuration should be listed. 
![image](https://github.com/goauthentik/authentik/assets/542109/54abc7f0-b9cb-4914-b163-4312838c3983)
Working user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0`

**Screenshots**
Shown above 

**Logs**
Output of docker-compose logs or kubectl logs respectively
`{"auth_via": "session", "event": "/api/v3/outposts/instances/", "host": "authentik.io", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 23, "remote": "10.26.1.61", "request_id": "56caa75eeb3144dda1a3c4b0d0810fe2", "runtime": 74, "scheme": "https", "status": 400, "timestamp": "2023-06-23T16:53:42.065198", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15"}`

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.4
-   Deployment: helm kubernetes

**Additional context**
- Stricly using safari as it supports passkey with webauthn.

**Comment by BeryJu** [comment] 2023-06-23 22:10
duplicate of #4155, fixed in main and will be released on 2023.6 early next week

**Closed by BeryJu** 2023-06-23 22:10 UTC
Labels: bug
