### ISSUE TITLE
Could not create unique index error when upgrading

### ISSUE THREAD

**Issue by davidus05** [goauthentik/authentik#5264] opened 2023-04-16 22:27 UTC
**Describe the bug**
I am stuck at version 2023.1.3 and cannot upgrade to any newer version, as an error occurs while doing migration. The errors below are shown and the containers are stuck in a bootloop.

**To Reproduce**
1. Download the new docker-compose file
2. Running docker-compose up (without -d)

**Expected behavior**
Upgrade should happen

**Logs**
```
postgresql_1  | 2023-04-16 22:23:07.684 UTC [279] ERROR:  could not create unique index "authentik_policies_policy_name_48caa747_uniq"
postgresql_1  | 2023-04-16 22:23:07.684 UTC [279] DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
postgresql_1  | 2023-04-16 22:23:07.684 UTC [279] STATEMENT:  ALTER TABLE "authentik_policies_policy" ADD CONSTRAINT "authentik_policies_policy_name_48caa747_uniq" UNIQUE ("name")
worker_1      |   Applying authentik_policies.0010_alter_policy_name...Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
worker_1      |     return self.cursor.execute(sql, params)
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
worker_1      |     return super().execute(*args, **kwargs)
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      | psycopg2.errors.UniqueViolation: could not create unique index "authentik_policies_policy_name_48caa747_uniq"
worker_1      | DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
worker_1      | 
worker_1      | 
worker_1      | The above exception was the direct cause of the following exception:
worker_1      | 
worker_1      | Traceback (most recent call last):
worker_1      |   File "<frozen runpy>", line 198, in _run_module_as_main
worker_1      |   File "<frozen runpy>", line 88, in _run_code
worker_1      |   File "/lifecycle/migrate.py", line 96, in <module>
worker_1      |     execute_from_command_line(["", "migrate"])
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
worker_1      |     utility.execute()
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
worker_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
worker_1      |     self.execute(*args, **cmd_options)
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
worker_1      |     output = self.handle(*args, **options)
worker_1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
worker_1      |     res = handle_func(*args, **kwargs)
worker_1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
worker_1      |     post_migrate_state = executor.migrate(
worker_1      |                          ^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
worker_1      |     state = self._migrate_all_forwards(
worker_1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
worker_1      |     state = self.apply_migration(
worker_1      |             ^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
worker_1      |     state = migration.apply(state, schema_editor)
worker_1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
worker_1      |     operation.database_forwards(
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
worker_1      |     schema_editor.alter_field(from_model, from_field, to_field)
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
worker_1      |     self._alter_field(
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 245, in _alter_field
worker_1      |     super()._alter_field(
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1045, in _alter_field
worker_1      |     self.execute(self._create_unique_sql(model, [new_field]))
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
worker_1      |     cursor.execute(sql, params)
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
worker_1      |     return self._execute_with_wrappers(
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
worker_1      |     return executor(sql, params, many, context)
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
worker_1      |     with self.db.wrap_database_errors:
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
worker_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
worker_1      |     return self.cursor.execute(sql, params)
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      |   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
worker_1      |     return super().execute(*args, **kwargs)
worker_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker_1      | django.db.utils.IntegrityError: could not create unique index "authentik_policies_policy_name_48caa747_uniq"
worker_1      | DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
worker_1      | 
root_worker_1 exited with code 1
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.7759185, "path": "authentik.admin.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.77747, "path": "authentik.crypto.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.7822535, "path": "authentik.events.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.7839577, "path": "authentik.outposts.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.7966392, "path": "authentik.policies.reputation.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8086178, "path": "authentik.providers.scim.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8107939, "path": "authentik.sources.ldap.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8126554, "path": "authentik.sources.plex.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8206425, "path": "authentik.stages.authenticator_static.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8215597, "path": "authentik.stages.authenticator_totp.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.8261347, "path": "authentik.stages.authenticator_validate.settings"}
server_1      | {"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683789.844698, "path": "authentik.blueprints.settings"}
server_1      | {"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1681683789.8450105, "version": "2023.4.0"}
worker_1      | {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683790.8400285, "file": "/authentik/lib/default.yml"}
worker_1      | {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683790.8414998, "count": 16}
worker_1      | {"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1681683790.8423922}
worker_1      | {"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1681683790.8543918}
worker_1      | {"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1681683790.8588204}
worker_1      | {"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1681683790.8596928}
worker_1      | {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683791.4554706, "file": "/authentik/lib/default.yml"}
worker_1      | {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1681683791.456793, "count": 16}
server_1      | {"event": "Loaded GeoIP database", "last_write": 1681469360.0, "level": "info", "logger": "authentik.events.geo", "pid": 9, "timestamp": "2023-04-16T22:23:11.536097"}
worker_1      | 2023-04-16 22:23:11 [info     ] applying django migrations
worker_1      | 2023-04-16 22:23:11 [info     ] waiting to acquire database lock
server_1      | {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 9, "task_id": "3bc8d663-2260-405f-9003-31ac2ddfd3d0", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-04-16T22:23:12.390122"}
server_1      | {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 9, "task_id": "a71f58c8-3d39-4ef5-be19-32fd5f0f5abb", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-04-16T22:23:12.393386"}
server_1      | Operations to perform:
server_1      |   Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, otp_static, otp_totp, sessions
server_1      | Running migrations:
postgresql_1  | 2023-04-16 22:23:13.664 UTC [282] ERROR:  could not create unique index "authentik_policies_policy_name_48caa747_uniq"
postgresql_1  | 2023-04-16 22:23:13.664 UTC [282] DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
postgresql_1  | 2023-04-16 22:23:13.664 UTC [282] STATEMENT:  ALTER TABLE "authentik_policies_policy" ADD CONSTRAINT "authentik_policies_policy_name_48caa747_uniq" UNIQUE ("name")
server_1      |   Applying authentik_policies.0010_alter_policy_name...Traceback (most recent call last):
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
server_1      |     return self.cursor.execute(sql, params)
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
server_1      |     return super().execute(*args, **kwargs)
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      | psycopg2.errors.UniqueViolation: could not create unique index "authentik_policies_policy_name_48caa747_uniq"
server_1      | DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
server_1      | 
server_1      | 
server_1      | The above exception was the direct cause of the following exception:
server_1      | 
server_1      | Traceback (most recent call last):
server_1      |   File "<frozen runpy>", line 198, in _run_module_as_main
server_1      |   File "<frozen runpy>", line 88, in _run_code
server_1      |   File "/lifecycle/migrate.py", line 96, in <module>
server_1      |     execute_from_command_line(["", "migrate"])
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
server_1      |     utility.execute()
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
server_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
server_1      |     self.execute(*args, **cmd_options)
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
server_1      |     output = self.handle(*args, **options)
server_1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
server_1      |     res = handle_func(*args, **kwargs)
server_1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
server_1      |     post_migrate_state = executor.migrate(
server_1      |                          ^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
server_1      |     state = self._migrate_all_forwards(
server_1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
server_1      |     state = self.apply_migration(
server_1      |             ^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
server_1      |     state = migration.apply(state, schema_editor)
server_1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
server_1      |     operation.database_forwards(
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
server_1      |     schema_editor.alter_field(from_model, from_field, to_field)
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
server_1      |     self._alter_field(
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 245, in _alter_field
server_1      |     super()._alter_field(
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1045, in _alter_field
server_1      |     self.execute(self._create_unique_sql(model, [new_field]))
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
server_1      |     cursor.execute(sql, params)
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
server_1      |     return self._execute_with_wrappers(
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
server_1      |     return executor(sql, params, many, context)
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
server_1      |     with self.db.wrap_database_errors:
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
server_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
server_1      |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
server_1      |     return self.cursor.execute(sql, params)
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      |   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
server_1      |     return super().execute(*args, **kwargs)
server_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
server_1      | django.db.utils.IntegrityError: could not create unique index "authentik_policies_policy_name_48caa747_uniq"
server_1      | DETAIL:  Key (name)=(test-not-app-password_2) is duplicated.
server_1      | 
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment] 2023-05-17 08:31
duplicate of #5650, which has a workaround included

**Closed by BeryJu** 2023-05-17 08:31 UTC
Labels: bug
