### ISSUE TITLE
GET /api/v3/flows/executor/default-authentication-flow/

### ISSUE THREAD

**Issue by Arragon5xpwm** [goauthentik/authentik#9432] opened 2024-04-25 15:53 UTC
**Describe the bug**

**To Reproduce**
1. Go to Authentik Login page
2. Instantly get "Something went wrong! Please try again later."
3. See error

**Expected behavior**
Login with username / password less / federated login button

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/50996723/52882aa8-8f02-43d6-8bb8-aacd5dfafd98)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 95, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 172, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 243, in get_challenge
    source_challenge.is_valid()
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 220, in is_valid
    assert hasattr(self, 'initial_data'), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.0
- Deployment: docker-compose

**Comment by BeryJu** [comment] 2024-04-25 21:00
This will be fixed in 2024.4.1 which will be out probably tomorrow and is caused by plex/apple sources. You can use https://docs.goauthentik.io/docs/troubleshooting/login as a workaround to log in or you can use this image for the time being `ghcr.io/goauthentik/dev-server:gh-version-2024.4`

**Closed by BeryJu** 2024-04-25 21:00 UTC
