### ISSUE TITLE
i18n email translation

### ISSUE THREAD

**Issue by MrMuster** [goauthentik/authentik#3885] opened 2022-10-26 12:26 UTC
**Describe the bug**
The predefined email templates are not translated when sending them using a changed locale. 

**To Reproduce**
1. Set the tenant attributes to.
`settings:
  locale: de
`
Everything is now successfully translated to German.
2. Activate the default recovery flow with the default "Password Reset" email template.
3. Either use "Email Recovery link" in the Admin Panel or use the default-recovery-flow as logged out user.
4. The email that is sent is always in English.

**Expected behavior**
As the email template [password_reset.html](https://github.com/goauthentik/authentik/blob/main/authentik/stages/email/templates/email/password_reset.html) contains the i18n tags "blocktrans" I would expect that the messages are translated to German.
The translation for these messages exists in [django.po](https://github.com/goauthentik/authentik/blob/main/locale/de/LC_MESSAGES/django.po#L1571).

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.0
 - Deployment: docker-compose

**Comment by MrMuster** [comment] 2022-11-22 11:59
Unfortunately the translation of the password reset email is still not working.
I tried authentik version 2022.10.1 which contains the commit. 

I set the tenant attributes and the user attributes to `settings: locale: de`

**Comment by BeryJu** [comment] 2022-11-22 20:40
So while the tests added above worked as intended, the actual issue for this not working is a lot simpler....the previous releases didn't include the translated locale files in the final docker images...so they were never loaded properly. This will be fixed in 2022.11.1

**Closed** 2022-11-22 20:41 UTC
Labels: bug
